config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'ngram/index'
  get 'ngram/show'
  get 'ngram/create'
  get 'ngram/search'
  get 'project_issues/index'
  # get "pages/home"
  resource :session, only: %i[new create destroy]
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  delete '/logout', to: 'sessions#destroy', as: :logout
  post '/search', to: 'projects#search'
  post '/search_insights', to: 'projects#search_insights'
  post '/search_ngram', to: 'projects#search_ngram'
  get '/projects/modal', to: 'projects#modal', as: :modal
  get '/projects/export_zip', to: 'projects#export_zip_file', as: :export_zip_file
  post '/projects/categories_select', to: 'projects#category_select', as: :category_select
  get 'categories', to: 'projects#categories'
  resources :projects
  resources :keywords
  resources :users
  root 'pages#home'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :projects, dependent: :destroy
  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize_user!, only: %i[edit update destroy]
  skip_before_action :require_login, only: %i[new create]
  allow_unauthenticated_access only: %i[new create]
  before_action :set_user, only: %i[show edit update destroy]
  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      terminate_session if Current.session.present?
      start_new_session_for(@user)
      redirect_to after_authentication_url, notice: 'Account created and logged in!'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.expect(user: %i[name email_address password password_confirmation])
  end
end

# def authorize_user!
#   redirect_to root_path, alert: "Not authorized." unless @user == current_user
# end

app/views/users/new.html.erb
<%= form_with model: @user, url: users_path, multipart: true, class: "max-w-xl mx-auto my-20 p-10 bg-white rounded", data: { controller: "modals", action: "turbo:submit-start->modals#open" } do |form| %>
<h2 class="text-2xl font-bold mb-6">New User</h2>
<% if  @user.errors.any? %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
    <h2 class="font-bold mb-2">Please fix the following errors:</h2>
    <ul>
      <%  @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div class="mb-4">
    <%= form.label :email_address, class: "block text-sm font-medium text-gray-700 mb-1"  %>
    <%= form.text_field :email_address, class: "w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring focus:border-blue-300" %>
  </div>

  <div class="mb-4">
    <%= form.label :password, class: "block text-sm font-medium text-gray-700 mb-1"  %>
    <%= form.text_field :password, class: "w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring focus:border-blue-300" %>
  </div>

  
  
   <!-- Submit -->
  <div class="text-center">
    <%= form.submit "Submit", class: "bg-zinc-400 hover:bg-zinc-500 text-white font-semibold px-6 py-2 rounded w-full" %>
  </div>

<% end %>