config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'ngram/index'
  get 'ngram/show'
  get 'ngram/create'
  get 'ngram/search'
  get 'project_issues/index'
  # get "pages/home"
  resource :session, only: %i[new create destroy]
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  delete '/logout', to: 'sessions#destroy', as: :logout
  post '/search', to: 'projects#search'
  post '/search_insights', to: 'projects#search_insights'
  post '/search_ngram', to: 'projects#search_ngram'
  get '/projects/modal', to: 'projects#modal', as: :modal
  get '/projects/export_zip', to: 'projects#export_zip_file', as: :export_zip_file
  post '/projects/categories_select', to: 'projects#category_select', as: :category_select
  get 'categories', to: 'projects#categories'
  resources :projects
  resources :keywords
  resources :users
  root 'pages#home'
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  belongs_to :user
  has_many :keywords, dependent: :destroy
  has_many :ngrams, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validate :projects_count_within_limit, on: :create
  accepts_nested_attributes_for :keywords, allow_destroy: true
  before_destroy :destroy_keywords_in_batches
  PROJECT_LIMIT = 100

  def projects_count_within_limit
    return unless user.projects.reload.count >= PROJECT_LIMIT

    errors.add(:base, 'Exceeded projects limit')
    Rails.logger.debug errors.full_messages
  end

  def destroy_keywords_in_batches
    keywords.in_batches(of: 1000) do |batch|
      batch.delete_all
      sleep(0.1)
    end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :log_params
  before_action :set_project, only: %i[show edit update destroy]
  include Paginatable
  include ProjectViewData
  include PhraseParser
  include ProjectsHelper
  include ExportToZip
  include ImportKeywords
  include LoadInSuggestions
  include AggregateCategories

  # include ExportProcessing
  require 'csv'
  require 'zip'
  require 'benchmark'
  require 'activerecord-import'
  def log_params
    Rails.logger.debug { ">>> #{controller_name}##{action_name} params: #{params.to_unsafe_h}" }
  end

  def project_params
    params.expect(
      project: [:name,
                { keywords_attributes: %i[id name search_volume url est_traffic keyword_category _destroy] }]
    )
  end

  # all projects
  def index
    @current_page = current_page(3)
    @projects = Project
                .where(user: current_user)
    @current_page_insights = current_page(6)
    @insights_per_page = 6
    @projectsInsights = paginate_project_insights[:data]
    @total_project_pages = paginate_project_insights[:total_pages]
    @insights = Insight.new(current_user)
  end

  # individual projects
  def show
    project_id_tables # concern which processes the data
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def export_zip_file
    @project = Project.find(params[:project_id])
    project_id_tables(100_000, 100_000, 10_000)
    export_zip
  end

  def search
    session[:kw_query] = params[:query] # setting query for kw filtering
    project_id = params[:project_id] # pulling project id from beforeaction in project_view
    @keywords = Keyword.search(params[:query], project_id) # utilizing search method in kw model
    @table_config = project_id_kw_table # pulling from projects_helper
    # respond_to(&:turbo_stream)
  end

  def search_insights
    session[:url_query] = params[:query]
    project_id = params[:project_id]
    @url_list = Keyword.search_insights(params[:query], project_id)
    # respond_to(&:turbo_stream)
  end

  def search_categories
    session[:category_query] = params[:query]
    project_id = params[:project_id]
    @categories = @top_categories
                  .where(project_id: project_id)
                  .search(params[:query], project_id)
                  .limit(10)
    # respond_to(&:turbo_stream)
  end

  def search_ngram
    session[:ngram_query] = params[:query]
    project_id = params[:project_id]
    @phrases = Ngram
               .search(params[:query], project_id)
               .limit(100)
               .order('weighted_frequency DESC')
    # respond_to(&:turbo_stream)
  end

  def new
    @project = Project.new
    @project.keywords.build
  end

  def edit; end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      if params[:project][:csv_file].present?
        begin
          import_keywords_from_csv(@project, params[:project][:csv_file])
        rescue BadHeaders => e
          @project.delete
          @project.errors.add(:base, e.message)
          render :new, status: :unprocessable_entity and return
        rescue UploadLimit => e
          @project.delete
          @project.errors.add(:base, e.message)
          render :new, status: :unprocessable_entity and return
        end
        key_holder = []
        url_pattern.each do |key|
          key_holder << key
        end
        render turbo_stream: turbo_stream
                             .update('modal',
                                     partial: 'components/modals/category_selection_form',
                                     locals: { key_holder: key_holder })
        kw_to_ngram if params[:accept_ngram].present?
        return
      end
      respond_to do |format|
        format.html { redirect_to @project }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def categories
    @project = Project.find(params[:project_id])
    @items = url_pattern
    key_holder = []
    @items.each { |key| key_holder << key }

    render partial: 'components/modals/categories',
           locals: { key_holder: key_holder, brand: params[:brand] },
           layout: false
  end

  def modal
    @project = Project.new
    @project.keywords.build
  end

  def extract_folder(url)
    clean_url = url.to_s.downcase
    clean_url[%r{\.\w+/([^/]+)}, 1]&.tr('-', ' ')
  end

  def keyword_import(updated_keywords)
    return unless updated_keywords.any?

    Keyword.import(
      updated_keywords,
      on_duplicate_key_update: {
        conflict_target: [:id],
        columns: [:keyword_category]
      }
    )
    updated_keywords.clear
  end

  def category_select
    selected = params[:selected_categories] || {}
    project_id = params[:project_id]
    @project = Project.find(project_id)

    if selected.blank?
      redirect_to project_path(project_id), notice: 'No categories have been selected.'
      return
    end

    category_volumes = Hash.new(0)

    updated_keywords = []

    Keyword.where(project_id: project_id).find_in_batches(batch_size: 500) do |batch| # this should be a standalone method
      sleep(0.1)
      batch.each do |kw|
        first_folder = extract_folder(kw.url)
        next if first_folder.nil?

        aggregate_categories(selected, first_folder, category_volumes, kw) # located in aggregate_categories
      end
    end
    # I have the categories {keyword => 200} etc
    # now I need to find the best suited category in case the first folder contains a compound phrase
    # cycle through each kw in batches of 500 and see if the first folder has any items from the category_volumes
    #
    sorted_volumes = category_volumes.sort_by { |_key, value| value }.reverse.to_h
    Keyword.where(project_id: project_id).find_in_batches(batch_size: 500) do |batch|
      sleep(0.1)
      batch.each do |keyword|
        first_folder = extract_folder(keyword.url)
        if first_folder.blank?
          keyword.keyword_category = '(Blank)'
          updated_keywords << keyword
          next
        else
          assign_categories(first_folder, sorted_volumes, keyword) # located in "aggregate_categories"
          updated_keywords << keyword
        end
      end
      keyword_import(updated_keywords)
    end
    # now that I have the log to store category_volumes, I should rerun the function above, but this time assign the keyword categories
    redirect_to project_path(project_id), notice: 'Categories applied to matching URLs'
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project.keywords.in_batches(of: 1000) do |batch|
      batch.delete_all
      sleep(0.1)
    end
    @project.destroy
    redirect_to projects_path
  end

  private

  def set_project
    @project = current_user.projects.find(params[:id])
    Rails.logger.debug { "setting project! #{@project}" }
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
  def parent_wrapper = 'bg-white text-gray-600 text-left font-medium text-sm flex-1 mt-4 px-5 rounded-sm shadow-md h-60'

  def table_body_styling
    {
      row_border: 'border border-dashed border-red-500',
      index_styling: 'border-x border-dashed border-red-500 p-0.5 px-1 text-center h-5 w-4',
      name_styling: 'p-0.5 px-1 max-w-40 overflow-hidden truncate whitespace-nowrap flex-1',
      keyword_styling: 'px-5 px-1 w-4 overflow-hidden truncate whitespace-nowrap'
    }
  end

  def project_id_kw_table
    {
      title: 'Keywords',
      columns: ['#', 'Keyword', 'Search Volume'],
      entry_key: 'name',
      styling: {
        parent_wrapper: parent_wrapper,
        table_scroll_behavior: 'overflow-y-scroll h-3/4 w-full',
        table_header_styling: 'bg-neutral-200 text-center',
        table_heading: 'mt-0 mb-4',

        table_body_styling: {
          row_border: 'border border-dashed border-red-500',
          index_styling: 'border-x border-dashed border-red-500 p-0.5 px-1 text-center w-2',
          name_styling: ' px-1 max-w-20 overflow-hidden truncate whitespace-nowrap text-ellipsis',
          keyword_styling: ' px-1 w-5 overflow-hidden truncate whitespace-nowrap text-ellipsis '
        }

      },
      include: {
        kw_count: true
      }
    }
  end

  def project_id_insights_table
    {
      title: 'URLs',
      columns: ['#', 'URL', 'SV', 'Est Traffic', 'KW Count'],
      urls: @top_urls,
      entry_key: 'name',
      styling: {
        parent_wrapper: parent_wrapper,
        table_header_styling: 'text-red-500 text-sm bg-white ',
        table_scroll_behavior: 'overflow-y-scroll w-full flex-1 h-3/4 max-h-60',
        overflow: 'overflow-y-scroll ',
        table_body_styling: table_body_styling
      },

      include: {
        traffic: true,
        kw_count: true
      }
    }
  end

  def project_id_category_table
    {
      title: 'Categories',
      columns: ['#', 'Category', 'Volume', 'Est. Traffic', 'KW Count'],
      entries: @top_categories,
      entry_key: 'name',
      styling: {
        parent_wrapper: parent_wrapper,
        table_header_styling: 'text-red-500 text-sm bg-white ',
        table_scroll_behavior: 'overflow-y-scroll w-full flex-1  h-3/4 max-h-60',
        overflow: 'overflow-y-scroll ',
        table_body_styling: table_body_styling
      },
      table_primary_field: 'url'

    }
  end

  def project_id_ngram_table
    {
      title: 'Phrases',
      columns: ['#', 'Phrase', 'Weighted Freq.', 'Count'],
      entries: @ngrams,
      entry_key: 'phrase',
      styling: {
        parent_wrapper: parent_wrapper,
        table_header_styling: 'text-red-500 text-sm bg-white ',
        table_scroll_behavior: 'overflow-y-scroll w-full flex-1 h-3/4 max-h-65',
        overflow: 'overflow-y-scroll ',
        table_body_styling: table_body_styling

      },
      table_primary_field: 'url',
      include: {
        kw_count: true
      }

    }
  end

  def project_index_summary
    {
      title: 'Projects by The Numbers',
      columns: [],
      entry_key: 'keyword_count',
      styling: {
        parent_wrapper: 'bg-zinc-500 row-span-3 col-span-2 text-left font-medium text-white max-h-300 mt-4 px-5 rounded-sm shadow-md',
        table_scroll_behavior: 'overflow-y-scroll max-h-150',
        table_header_styling: 'nil',

        table_body_styling: {
          row_border: 'border border-dashed border-red-500',
          index_styling: 'border-x border-dashed border-red-500 p-0.5 px-1 text-center w-2',
          name_styling: ' px-1 max-w-20 overflow-hidden truncate whitespace-nowrap text-ellipsis',
          keyword_styling: ' px-5 w-5 overflow-hidden truncate whitespace-nowrap text-ellipsis '
        }

      },
      include: {
        kw_count: true
      }
    }
  end

  def kw_columns
    ['#', 'Keyword', 'Search Volume']
  end

  def project_columns
    ['#', 'Name', 'Insight']
  end

  def glass_red_chart_options
    {
      colors: ['#FF4D4D', '#FFD1D1', '#FF8888', '#FF9999'],
      height: '100',
      library: {
        # this is Chart.js "options" (no extra :options wrapper)
        responsive: true,
        maintainAspectRatio: false,
        backgroundColor: 'rgba(0,255,255,0.4)', # slightly glassy
        plugins: {
          title: {
            fullSize: false,
            font: { size: 14 }
          },
          datalabels: {
            display: true,
            anchor: 'end',
            align: 'top',
            color: 'rgba(255,255,255,0.9)',
            font: { size: 14, family: 'Inter', weight: '600' },
            formatter: ->(value) { value } # shows count value on top of each bar
          },
          legend: {
            display: false
            # If you later enable legend and want spacing:
            # labels: { boxPadding: 4 }
          },

          tooltip: {
            backgroundColor: 'rgba(255, 255, 255, 0.85)',
            borderColor: 'rgba(255, 77, 77, 0.3)',
            borderWidth: 1,
            titleColor: '#FF4D4D',
            bodyColor: '#444',
            titleFont: { size: 16, weight: '300' },
            bodyFont: { size: 12 },
            cornerRadius: 6,
            padding: 8
          }
        },
        maxBarThickness: 50,

        scales: {
          x: { display: true,
               title: { display: true },
               grid: { color: 'rgba(255, 255, 255, 0.05)' } },
          y: {
            ticks: {
              color: 'rgba(255, 255, 255, 0.8)',
              font: { size: 16 }
            },
            grid: { color: 'rgba(255, 255, 255, 0.08)' }

          }
        }
      }
    }
  end

  def glass_red_pie_options
    {
      colors: [
        '#FF4D4D', '#e5b443', '#a1a1aa', '#FFD1D1',
        '#d9a23a', '#FF8888', '#FF9999', '#f1cb4b'
      ],
      library: {
        type: 'pie', # Let Chartkick know the chart type
        options: {
          responsive: true,
          backgroundColor: '#ffffff',
          plugins: {
            tooltip: {
              backgroundColor: 'rgba(255, 255, 255, 0.85)',
              borderColor: 'rgba(255, 77, 77, 0.3)',
              borderWidth: 1,
              titleColor: '#FF4D4D',
              bodyColor: '#444',
              titleFont: {
                size: 14,
                weight: '600'
              },
              bodyFont: {
                size: 12
              },
              cornerRadius: 6,
              boxPadding: 4
            }
          }
        },
        overrides: {
          pie: {
            plugins: {
              legend: {
                display: true,
                position: 'left',
                align: 'start',
                labels: {
                  boxWidth: 30,
                  padding: 10,
                  color: '#333',
                  font: {
                    size: 14,
                    family: 'Inter'
                  }
                }
              }
            }
          }
        }
      }
    }
  end
end

app/views/projects/_category_selection.html.erb
<% @items.each do |key, value| %>
  <%key_holder << key %>
<% end %>
<div class="modal">
  <%= form_with url: categories_select_path, method:post, local: true do |form|%>
    <% key_holder.each do |category|  %>
      <div class="category-checkbox">
        <%= check_box_tag "selected_categories[]", category,
                          false,
                          id: "category_#{category.parameterize}" %>
        <%= label_tag "category_#{category.parameterize}", category.humanize %>
      </div>
    <%end%>
  <%= submit_tag "Save Selected Categories" %>
  <% end %>
</div>

app/views/projects/create.turbo_stream.erb
<turbo-stream action="update" target="modal">
  <template>
    <div class="modal" data-project-id="<%= @project.id %>">
      <h2>Processing your project…</h2>
    <div class="spinner"></div>
    <div>
    <%= link_to "Close", "#", data: {
        controller: "modals",
        action: "modals#close"
      }, class: "cancel-button" %>
    </div>
  </template>
</turbo-stream>

app/views/projects/edit.html.erb
<%= form_with model: Project.first do |form| %>
<%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/projects/index.html.erb
<div class="max-w-lg mx-auto my-10 p-10">
  <div class="w-full content-center">
    <%= render partial: "/components/tables/keyword_table",
    locals: {
      entries: @projects,
      current_page: @current_page,
      table_config: home_projects_table,
      styling: home_projects_table[:styling],
      entry_key: home_projects_table[:entry_key],
    } %>
  </div>
  <div
    class="
      bg-zinc-500 text-white p-6 my-5 shadow-lg rounded-md w-4xl m-auto w-full
    "
  >
    <ul class="space-y-2">
      <li class="flex justify-between border-b border-red-400 pb-1">
        <span>1 Total Keywords</span>
        <span><%= number_with_delimiter(@insights.keyword_count, precision: 1) %></span>
      </li>
      <li class="flex justify-between border-b border-red-400 pb-1">
        <span>2 Total nGrams</span>
        <span><%= number_with_delimiter(@insights.ngram_count) %></span>
      </li>
      <li class="flex justify-between border-b border-red-400 pb-1">
        <span>3 Number of URL Categories</span>
        <span><%= @insights.categories.count %></span>
      </li>
    </ul>
  </div>
  <div class="m-auto w-full max-w-md">
    <%= link_to "Add New Project",
    new_project_path,
    class:
      "text-center block bg-red-500 text-white p-2 px-5 drop-shadow-md content-center " %>
  </div>
</div>

app/views/projects/modal.html.erb
<%= render partial: "/components/modals/keyword_categorization", locals: { 

    } %>

app/views/projects/new.html.erb
<%= form_with model: @project, url: projects_path, multipart: true, class: "max-w-xl mx-auto my-20 p-10 bg-white rounded", data: { controller: "modals", action: "turbo:submit-start->modals#open" } do |form| %>
<h2 class="text-2xl font-bold mb-6">New Project</h2>
<% if @project.errors.any? %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
    <h2 class="font-bold mb-2">Please fix the following errors:</h2>
    <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div class="mb-4">
    <%= form.label :name, class: "block text-sm font-medium text-gray-700 mb-1"  %>
    <%= form.text_field :name, required: true, class: "w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring focus:border-blue-300" %>
  </div>
  </div>
  <div class="mb-6">
<%= form.label :csv_file, "Upload CSV", class: "block text-sm font-medium text-gray-700 mb-1" %>
    <%= form.file_field :csv_file, accept: ".csv", required: true, class: "w-full border border-gray-300 rounded px-3 py-2 bg-white file:mr-4 file:py-2 file:px-4 file:rounded file:border-0 file:bg-red-700 file:text-white hover:file:bg-red-700" %>
  </div>
  <%= check_box_tag 'accept_ngram'%>
  <%= label_tag('accept ngram',  "Process Ngram (Takes Longer)") %>
  
   <!-- Submit -->
  <div class="text-center">
    <%= form.submit "Create Project", class: "bg-zinc-400 hover:bg-zinc-500 text-white font-semibold px-6 py-2 rounded w-full" %>
  </div>
  

<% end %>

app/views/projects/search.turbo_stream.erb
<%= turbo_stream.update "keyword_table" do %>
  <%= render partial: "components/tables/keyword_table", locals: {
    entries: @keywords,
    current_page: false,
    table_config: @table_config,
    styling: @table_config[:styling],
    entry_key: @table_config[:entry_key]
  } %>
<% end %>

app/views/projects/search_categories.turbo_stream.erb
     <%= turbo_frame_tag "search_categories_table" do %>
     <%= render partial: "/components/tables/keyword_table", locals: { 
      entries: @categories,
      includes: project_id_insights_table[:include], 
      current_page: false,
      table_config: project_id_category_table,
      styling: project_id_category_table[:styling],
      entry_key: project_id_category_table[:entry_key]
      }%>
    <%end %> 

app/views/projects/search_insights.turbo_stream.erb
<%= turbo_stream.update "search_insights_table" do %>
  <%= render partial: "components/tables/keyword_table", locals: {
    entries: @url_list,
    includes: project_id_insights_table[:include],
    current_page: false,
    table_config: project_id_insights_table,
    styling: project_id_insights_table[:styling],
    entry_key: project_id_insights_table[:entry_key]
  } %>
<% end %>

app/views/projects/search_ngram.turbo_stream.erb
<%= turbo_stream.update "phrase_table" do %>
  <%= render partial: "components/tables/keyword_table", locals: {
    entries: @phrases,
    total_pages: @total_pages,
    current_page: false,
    table_config: project_id_ngram_table,
    styling: project_id_ngram_table[:styling],
    entry_key: project_id_ngram_table[:entry_key],
    includes: project_id_ngram_table[:include], 
  } %>
<% end %>

app/views/projects/show.html.erb
<div
  class="
    flex items-center gap-1 mx-20 mt-5 px-10 justify-between m-auto bg-gray-200
    shadow-md
  "
>
  <!-- Project label -->
  <div class="flex items-center space-x-4 h-[50px]">
    <h2 class="text-md text-red-500 font-semibold">Choose A Project:</h2>
    <%= select_tag :project_id,
    options_from_collection_for_select(@projects, :id, :name),
    prompt: @project&.name || "Select a project",
    onchange: "if(this.value) Turbo.visit('/projects/' + this.value)",
    class: "bg-zinc-100 text-gray-500 text-sm px-3 p-2 " %>
  </div>
  <!-- Dropdown --> <!-- Delete button -->
  <div class="col-span-1 flex justify-end">
    <%= button_to "Delete",
    project_path(@project),
    method: :delete,
    data: {
      turbo_confirm: "Are you sure?",
    },
    class:
      "bg-red-600 hover:bg-red-700 text-white font-semibold px-3 py-1 rounded text-sm" %>
  </div>
</div>
<!-- Categories Chart -->
<div class="mx-10 my-5">
  <div class="grid grid-cols-6 gap-5 col-span-9 mx-10 my-5 content-center">
    <div class=" col-span-2">
      <div class="grid grid-cols-1 gap-1">
        <div
          class="
            mt-4 p-5 rounded-sm shadow-md bg-white backdrop-blur-sm border border-white/20
          "
        >
          <div class="h-full">
            <%= column_chart @keywords.group(:keyword_category).order("count_all DESC").count,
            **glass_red_chart_options,
            height: "200px",
            title: "Categories",
            ytitle: "KW Count" %>
          </div>
        </div>
        <div
          class="
            mt-4 p-5 rounded-sm shadow-md bg-white backdrop-blur-sm border border-white/20
          "
        >
          <%= column_chart @top_urls
            .limit(10)
            .map { |k| [k.name.sub(%r{^[^/]+}, ""), k.search_volume.to_i] },
          **glass_red_chart_options,
          height: "200px",
          title: "URLs",
          ytitle: "KW Count" %>
        </div>
        <!-- URL Chart -->
        <%= turbo_frame_tag "keyword_table" do %>
          <%= render partial: "/components/tables/keyword_table",
          locals: {
            entries: @keywords,
            current_page: @current_page,
            table_config: project_id_kw_table,
            styling: project_id_kw_table[:styling],
            entry_key: project_id_kw_table[:entry_key],
          } %>
        <% end %>

      </div>
    </div>
    <!-- URL Table -->
    <div class="col-span-3 h-full flex flex-col w-full gap-1">

      <%= turbo_frame_tag "search_insights_table" do %>
        <%= render partial: "/components/tables/keyword_table",
        locals: {
          entries: project_id_insights_table[:urls],
          includes: project_id_insights_table[:include],
          current_page: false,
          table_config: project_id_insights_table,
          styling: project_id_insights_table[:styling],
          entry_key: project_id_insights_table[:entry_key],
        } %>
      <% end %>
      <!-- Category Table -->
      <%= turbo_frame_tag "search_categories_table" do %>
        <%= render partial: "/components/tables/keyword_table",
        locals: {
          entries: project_id_category_table[:entries],
          includes: project_id_insights_table[:include],
          current_page: false,
          table_config: project_id_category_table,
          styling: project_id_category_table[:styling],
          entry_key: project_id_category_table[:entry_key],
        } %>
      <% end %>
      <!-- Phrase Table -->
      <%= turbo_frame_tag "phrase_table" do %>
        <%= render partial: "/components/tables/keyword_table",
        locals: {
          entries: project_id_ngram_table[:entries],
          total_pages: @total_pages,
          current_page: false,
          table_config: project_id_ngram_table,
          styling: project_id_ngram_table[:styling],
          entry_key: project_id_ngram_table[:entry_key],
          includes: project_id_ngram_table[:include],
        } %>
      <% end %>
    </div>
    <!-- Search Boxes -->
    <div class="gap-5 my-2 bg-white p-5">
      <!-- need to fix this box going all the way down -->
      <div class="flex-1 rounded items-center justify-center gap-5 mt-2 space-y-6">
        <span class="text-gray-500">Keywords</span>
        <%= form_with url: search_path, html: { class: "text-center" }, method: :post, data: { turbo_frame: "keyword_table" } do %>
          <div class="border-2 border-red-500 text-center rounded-sm align-middle">
            <%= text_field_tag :query,
            params[:query],
            placeholder: "Search",
            class:
              "text-center 2xl:w-20 2xl:text-lg md:w-15 md:text-xs text-red-500 w-2 p-1" %>
          </div>
          <%= hidden_field_tag :project_id, @project.id %>
          <%# <%= submit_tag "Search" %>
        <% end %>

      </div>
      <div class="flex-1 rounded items-center justify-center gap-5 mt-2 space-y-6">
        <span class="text-gray-500">URLs</span>
        <%= form_with url: search_insights_path, method: :post, data: { turbo_frame: "search_insights_table" } do %>
          <div class="border-2 border-red-500 text-center rounded-sm align-middle">
            <%= text_field_tag :query,
            params[:query],
            placeholder: "Search",
            class: "text-center 2xl:w-35 2xl:text-lg md:w-25 md:text-xs text-red-500  p-1" %>
          </div>
          <%= hidden_field_tag :project_id, @project.id %>
        <% end %>
      </div>

      <div class="flex-1 rounded items-center justify-center gap-5 mt-2 space-y-6">
        <span class="text-gray-500">Phrases</span>
        <%= form_with url: search_ngram_path, method: :post do %>
          <div class="border-2 border-red-500 text-center rounded-sm align-middle">
            <%= text_field_tag :query,
            params[:query],
            placeholder: "Search",
            class: "text-center 2xl:w-35 2xl:text-lg md:w-25 md:text-xs text-red-500  p-1" %>
            <%= hidden_field_tag :project_id, @project.id %>
          </div>
        <% end %>
      </div>

      <%= form_with url: export_zip_file_path, method: :get, target: "_blank", data: {turbo:"false"} do %>
        <%= hidden_field_tag :project_id, @project.id %>
        <%= submit_tag "Download CSV", class: "btn mt-5 text-sm" %>
      <% end %><%= print @project.name %>
    </div>

  </div>
  <%# <%= link_to "Edit", edit_project_path(@project) %>
  <%# <%= button_to "Delete", @project, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
  <%# <%= link_to "Back", project_path %>

</div>