config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'ngram/index'
  get 'ngram/show'
  get 'ngram/create'
  get 'ngram/search'
  get 'project_issues/index'
  # get "pages/home"
  resource :session, only: %i[new create destroy]
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  delete '/logout', to: 'sessions#destroy', as: :logout
  post '/search', to: 'projects#search'
  post '/search_insights', to: 'projects#search_insights'
  post '/search_ngram', to: 'projects#search_ngram'
  get '/projects/modal', to: 'projects#modal', as: :modal
  get '/projects/export_zip', to: 'projects#export_zip_file', as: :export_zip_file
  post '/projects/categories_select', to: 'projects#category_select', as: :category_select
  get 'categories', to: 'projects#categories'
  resources :projects
  resources :keywords
  resources :users
  root 'pages#home'
end

app/views/layouts/_navbar.html.erb
<div class ="flex md:justify-end flex-nowrap gap-6 p-4
      bg-gradient-to-r from-red-600 to-red-500
      text-white ">
      <div class ="max-w-7xl mx-auto px-10">
      <button id="menu-toggle" class="md:hidden text-align-left p-2 text-white rounded">
        ☰ Menu
      </button>
       <ul class="hidden md:flex gap-6 text-base xl:text-lg  align-middle" >
        <%= link_to "HUB", root_path, class:"py-2" %>
        <%= link_to "Add Projects", new_project_path, class:"rounded bg-white text-red-500 px-5 py-2"%>
        <%# <%= link_to "PROJECTS", projects_path, class:"py-2" %>
        <%# <%= link_to "KEYWORDS", keywords_path, class:"py-2" %> 
        <%# <p>PROFILE</p> %>
        <%= button_to "LOGOUT", logout_path, class:"rounded border-white bg-red text-white px-5 py-2", method: :delete if authenticated? %>
        </ul>

      </div>
       <nav id="mobile-menu" class="hidden md:hidden m-2 space-y-2 text-xl
       bg-white border border-gray-300 rounded shadow">
        <a href="#" class="block text-red-500 font-semibold hover:bg-red-600 hover:text-white m-4 p-1 rounded">Home</a>
        <a href="#" class="block text-red-500 font-semibold hover:bg-red-600 hover:text-white m-4 p-1 rounded">Projects</a>
        <%# <a href="#" class="block text-red-500 font-semibold hover:bg-red-600 hover:text-white m-4 p-1 rounded">Contact</a> %>
      </nav>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Keyword Analyzer" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    
  </head>

  <body class="bg-gray-100">
    <%= render "layouts/navbar"%>
    <% if flash[:notice] %>
      <div id="flash-notice" class="p-4 bg-green-200 text-green-800 rounded " data-controller="hide-on-click">
        <%= flash[:notice] %>
        <button class="cursor-pointer px-10" data-action="hide-on-click#hide">X</button>
      </div>
    <% end %>
    <main class="mx-auto px-10" id= "main">
    
    <%= yield  %>
    </main>
    
    <%= turbo_frame_tag "modal"%>
    
  </body>
</html>